SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE HasSP
	@CurrentAmmo int,
	@UsedAmmo int 
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRANSACTION
	INSERT INTO Has(CurrentAmmo, UsedAmmo) VALUES (@CurrentAmmo, @UsedAmmo);
	IF @@ERROR = 0
		COMMIT
	ELSE
		ROLLBACK
END
GO
